### ISSUE TITLE
Where do you call the dashboard "light.yaml"

### ISSUE THREAD

**Issue by Martinnygaard** [pqpxo/SWAKES_hassio#1]
Hi, im getting very inspired by the structure of your instance.
I can't figure out where you call the Lovelace YAML file for your different dashboards in the dashboard folder?

**Comment by Martinnygaard** [comment]
Never mind - i figured out it was UI controlled instead of YAML.
I've tried to base my 2.0 interface on yours layout. I really likes it!

**Comment by hcoohb** [comment]
Sorry to comment on this closed issue, but can you provide more details on how to set each dashboard code?
I cannot seem to edit the yaml seperately for each view from the UI... only for the whole dashboard.
And I cannot use the !include directive from the UI raw editor...
This does not work:
```yaml
views:
  - !include dashboards/system.yaml
```

**Comment by pqpxo** [comment]
> 
> 
> Sorry to comment on this closed issue, but can you provide more details on how to set each dashboard code?
> I cannot seem to edit the yaml seperately for each view from the UI... only for the whole dashboard.
> And I cannot use the !include directive from the UI raw editor...
> This does not work:
> 
> ```yaml
> views:
>   - !include dashboards/system.yaml
> ```

Hi there,
Apologies it may be that some of my old HA code has been uploaded alongside my new setup. Previously I used YAML mode to build my dashboards but now I'm doing it the lazy way and using the UI. What elements/pages are you having issues with?
