### ISSUE TITLE
Hi, i love your theme

### ISSUE THREAD

**Issue by Zeatles** [pqpxo/SWAKES_hassio#11]
Hi, i don't if was possibile, but could you share the name of lovelace theme?
Are you created by yourself or is a public theme?
thanks a lot

**Comment by pqpxo** [comment]
Hi there,

Here is the theme I use which is an existing theme which I've modified slightly ... 

https://github.com/pqpxo/SWAKES_hassio/blob/master/themes/noctis.yaml

**Comment by Zeatles** [comment]
Hi, thanks a lot for your help.
Only another question, could you tell me about the background image of the lovelace dashboard beacuse in the github project i didn’t find anything.
Thanks

Inviato da iPhone

**Comment by corgan2222** [comment]
I have also searched for the Background Image some time ago and couldn't find it. :)
