### ISSUE TITLE
Missing Home view

### ISSUE THREAD

**Issue by shyne99** [pqpxo/SWAKES_hassio#4]
Hi First of all, great work. I am a fan of what you did.

I wanted to implement similar stuff from what I've saw oon imgur, especially on your "Welcome" page, the home page with the phone status and stuff. I came here looking for the yaml with no luck.

So you think it would be possible for you to add them to the dashboards folder ? 

If you can't or do not want, it's also fine. 

Thank you, and again congrats on what you've done :)

**Comment by pqpxo** [comment]
Hi there!

Apologies for the mega late reply. I hardly come on GitHub to be honest. I'm currently going through a 'redesign' and will be updating the 'Welcome' page soon. However I'll try and upload the existing one shortly.
