### ISSUE TITLE
Theme used

### ISSUE THREAD

**Issue by mvereecken** [pqpxo/SWAKES_hassio#9]
I found this through Reddit where you answered in your post last week. I wonder what theme you're using (for fonts/colors/styling). Or is it completely customised for and by you? There are some very nice touches in there.

**Comment by mariusvanderwerff** [comment]
https://pastebin.com/tvyEGLTX?fbclid=IwAR0yQIepA21FPVhWQWiClYjENdxRGt7_IyoZpg7kYZIXHr5XeIPW8ZanWcE
